[project]
name = "MediaManager"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "David Sciacchettano", email = "david.sciacchettano@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "PySide6"
]

[project.optional-dependencies]
all = [
    "MediaManager[dev]"
]
dev = [
    "pytest",
    "pytest-qt",
    "ruff"
]


[project.scripts]
MediaManager = "MediaManager:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name="MediaManager"